# Use root/example as user/password credentials
version: '3.9'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    # volumes:
    #   - ./database/data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
